service: import-service
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::import-service-dev-serverlessdeploymentbucket-1hs17dz9g6baq/"
    - Effect: "Allow"
      Action: "s3:*"
      Resource:
        - "arn:aws:s3:::import-service-dev-serverlessdeploymentbucket-1hs17dz9g6baq/*"

functions:
  importProductsFile:
    handler: handler.importProductsList
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
         bucket: import-service-dev-serverlessdeploymentbucket-1hs17dz9g6baq
         event: s3:ObjectCreated:*
         rules:
            - prefix : uploaded/
         existing: true



